name: Deploy

on:
  push:
    branches: main
  workflow_dispatch:

env:
  DOCKER_IMAGE: ''
  GCP_CLOUD_RUN_SERVICE_NAME: mcpgrid-scraper


jobs:
  deploy:
    name: Deploy
    
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          echo "DOCKER_IMAGE=${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}/${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Confirm environment variables
        run: |
          echo ${{env.DOCKER_IMAGE}}

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.DOCKER_IMAGE }}" ./
          docker push "${{ env.DOCKER_IMAGE }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          job: ${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}
          region: ${{ vars.GCP_REGION }}
          image: ${{ env.DOCKER_IMAGE }}
          flags: |
            --max-retries=1
            --task-timeout=24h
            --parallelism=1
            --memory=1Gi
          secrets: |
            SMITHERY_API_KEY=SMITHERY_API_KEY:latest
            STORAGE_BACKET_NAME=SCRAPER_STORAGE_BACKET_NAME:latest
          env_vars: |
            STORAGE_BACKET_FOLDER=smithery
            SMITHERY_UPDATE_FREQ=72
            STORAGE_SERVICE_ACCOUNT_KEY=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
            

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

      
